Repository JetBrains-Research/TestSpark, pull requests merged in 2024-09, with the labels that each got.

#365 Update build.yml
  .github/workflows/build.yml
Labels: bug, Ready for review, In progress, Urgent

#354 Disable buttons during tests running
  src/main/kotlin/org/jetbrains/research/testspark/display/generatedTests/GeneratedTestsTabBuilder.kt
  src/main/kotlin/org/jetbrains/research/testspark/display/generatedTests/GeneratedTestsTabData.kt
  src/main/kotlin/org/jetbrains/research/testspark/display/generatedTests/TestCasePanelBuilder.kt
  src/main/kotlin/org/jetbrains/research/testspark/display/generatedTests/TopButtonsPanelBuilder.kt
Labels: bug, Ready for review, In progress

#342 Add empty LLM response handling
  src/main/kotlin/org/jetbrains/research/testspark/display/generatedTests/TestCasePanelBuilder.kt
  src/main/resources/properties/llm/LLMMessages.properties
Labels: bug, Ready for review, In progress

#292 Re-implement prompt builder & make it public
  core/build.gradle.kts
  core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/prompt/PromptBuilder.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/prompt/PromptKeyword.kt
  src/main/kotlin/org/jetbrains/research/testspark/helpers/PromptParserHelper.kt
  src/main/kotlin/org/jetbrains/research/testspark/settings/llm/LLMSettingsComponent.kt
  src/test/kotlin/org/jetbrains/research/testspark/core/generation/llm/prompt/PromptBuilderTest.kt
Labels: improvement, refactoring, Ready for review, In progress

#334 Fix error handling
  src/main/kotlin/org/jetbrains/research/testspark/tools/Pipeline.kt
Labels: bug, Ready for review, In progress

#340 Updated jacoco jars to 0.8.12
  build.gradle.kts
  lib/jacocoagent.jar
  lib/jacococli.jar
Labels: bug, Ready for review

#357 Modification prompt update
  core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/Utils.kt
Labels: bug, improvement, Ready for review

#364 Fix imports saving
  core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/LLMWithFeedbackCycle.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/data/TestSuiteGeneratedByLLM.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/strategies/JUnitTestSuiteParserStrategy.kt
Labels: bug, Ready for review

#363 Incorrect output in headless mode
  src/main/kotlin/org/jetbrains/research/testspark/appstarter/TestSparkStarter.kt
Labels: bug, Ready for review

#331 Close generated tests tab, if all test were deleted
  src/main/kotlin/org/jetbrains/research/testspark/display/generatedTests/TopButtonsPanelBuilder.kt
Labels: bug, Ready for review, In progress

#358 Fix execution cancellation
  src/main/kotlin/org/jetbrains/research/testspark/display/generatedTests/TestCasePanelBuilder.kt
  src/main/kotlin/org/jetbrains/research/testspark/display/generatedTests/TopButtonsPanelBuilder.kt
Labels: bug, Ready for review, In progress
