Repository JetBrains-Research/TestSpark, pull requests merged in 2024-10, with the labels that each got.

#370 Render uncompilable test suite if it was successfully parsed
  core/build.gradle.kts
  core/src/main/kotlin/org/jetbrains/research/testspark/core/data/Report.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/data/TestGenerationData.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/LLMWithFeedbackCycle.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/LLMProcessManager.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/PromptManager.kt
  src/main/resources/properties/llm/LLMMessages.properties
Labels: improvement, Ready for review, important, UI/UX

#362 Added opentest4j lib
  build.gradle.kts
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/data/dependencies/TestCompilationDependencies.kt
  lib/opentest4j-1.1.1.jar
Labels: bug, Ready for review

#343 Fix overflow of the input field for prompting an LLM
  src/main/kotlin/org/jetbrains/research/testspark/display/generatedTests/TestCasePanelBuilder.kt
Labels: bug, Ready for review

#380 Prompt serialization: use Kotlin's `Json` to treat special symbols
  src/main/kotlin/org/jetbrains/research/testspark/data/llm/JsonEncoding.kt
Labels: bug, Ready for review

#344 Restrict TestSpark action to suitable code types and fix generation for a line
  core/build.gradle.kts
  core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/prompt/PromptGenerator.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/prompt/configuration/Configuration.kt
  java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiClassWrapper.kt
  java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiHelper.kt
  java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiMethodWrapper.kt
  kotlin/src/main/kotlin/org/jetbrains/research/testspark/kotlin/KotlinPsiClassWrapper.kt
  kotlin/src/main/kotlin/org/jetbrains/research/testspark/kotlin/KotlinPsiHelper.kt
  kotlin/src/main/kotlin/org/jetbrains/research/testspark/kotlin/KotlinPsiMethodWrapper.kt
  langwrappers/src/main/kotlin/org/jetbrains/research/testspark/langwrappers/PsiComponents.kt
  src/main/kotlin/org/jetbrains/research/testspark/actions/TestSparkAction.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/ToolUtils.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/PromptManager.kt
  src/main/resources/properties/llm/LLMDefaults.properties
  src/test/kotlin/org/jetbrains/research/testspark/core/generation/llm/prompt/PromptBuilderTest.kt
Labels: bug, Ready for review, Urgent

#376 Locate `kotlinc` filepath via IntelliJ IDEA's bundled Kotlin plugin
  core/build.gradle.kts
  core/src/main/kotlin/org/jetbrains/research/testspark/core/exception/Exceptions.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/java/JavaTestCompiler.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/kotlin/KotlinTestCompiler.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/Pipeline.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/factories/TestCompilerFactory.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/Llm.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/LLMProcessManager.kt
  src/main/resources/META-INF/plugin.xml
  src/main/resources/properties/llm/LLMMessages.properties
Labels: Ready for review, Urgent

#346 Fix incorrect state after indicator cancellation
  core/build.gradle.kts
  core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/LLMWithFeedbackCycle.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/ToolUtils.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/openai/OpenAIRequestManager.kt
Labels: bug, Ready for review

#389 Add quotes around compilers' filepaths
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/java/JavaTestCompiler.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/kotlin/KotlinTestCompiler.kt
Labels: Ready for review, Urgent

#386 Migrate to IntelliJ Platform V2
  .github/workflows/build.yml
  .run/Run IDE for UI Tests.run.xml
  CONTRIBUTING.md
  build.gradle.kts
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  java/build.gradle.kts
  kotlin/build.gradle.kts
  langwrappers/build.gradle.kts
  src/main/kotlin/org/jetbrains/research/testspark/bundles/llm/LLMDefaultsBundle.kt
Labels: Ready for review, Urgent

#392 Saving Kotlin classfiles properly
  core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/LLMWithFeedbackCycle.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/TestCompiler.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/java/JavaTestCompiler.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/kotlin/KotlinTestCompiler.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/TestProcessor.kt
Labels: bug, Urgent

#393 Fix Issue 390: Better generation process monitor
  core/src/main/kotlin/org/jetbrains/research/testspark/core/progress/CustomProgressIndicator.kt
  src/main/kotlin/org/jetbrains/research/testspark/actions/controllers/TestGenerationController.kt
  src/main/kotlin/org/jetbrains/research/testspark/display/TestSparkDisplayManager.kt
  src/main/kotlin/org/jetbrains/research/testspark/display/custom/IJProgressIndicator.kt
  src/main/kotlin/org/jetbrains/research/testspark/display/generatedTests/GeneratedTestsTabBuilder.kt
  src/main/kotlin/org/jetbrains/research/testspark/progress/HeadlessProgressIndicator.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/Pipeline.kt
Labels: bug, Ready for review, Urgent

#394 Enhance subclass fetching for ultra light classes
  kotlin/src/main/kotlin/org/jetbrains/research/testspark/kotlin/KotlinPsiClassWrapper.kt
Labels: bug, Ready for review, Urgent

#406 Quote compilers' filepaths with "" for Windows
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/java/JavaTestCompiler.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/kotlin/KotlinTestCompiler.kt
Labels: Ready for review
