Repository JetBrains-Research/TestSpark, pull requests merged in 2024-06, with the labels that each got.

#228 improvement: Add Headless mode for LLM-based test generation
  build.gradle.kts
  runTestSparkHeadless.sh
  src/main/kotlin/org/jetbrains/research/testspark/appstarter/TestSparkStarter.kt
  src/main/kotlin/org/jetbrains/research/testspark/progress/HeadlessProgressIndicator.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/Pipeline.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/TestProcessor.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/Llm.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/error/LLMErrorManager.kt
  src/main/resources/META-INF/plugin.xml
Labels: Ready for review, Urgent

#220 Slow operations are prohibited on EDT
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/Llm.kt
  src/main/resources/properties/plugin/PluginMessages.properties
Labels: Ready for review

#223 [ICTL-910] New level of abstraction for PsiHelper
  core/src/main/kotlin/org/jetbrains/research/testspark/core/data/ClassType.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/prompt/PromptBuilder.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/prompt/configuration/Configuration.kt
  gradle.properties
  src/main/kotlin/org/jetbrains/research/testspark/actions/TestSparkAction.kt
  src/main/kotlin/org/jetbrains/research/testspark/appstarter/TestSparkStarter.kt
  src/main/kotlin/org/jetbrains/research/testspark/data/ProjectContext.kt
  src/main/kotlin/org/jetbrains/research/testspark/helpers/psi/PsiComponents.kt
  src/main/kotlin/org/jetbrains/research/testspark/helpers/psi/PsiHelperFactory.kt
  src/main/kotlin/org/jetbrains/research/testspark/helpers/psi/java/JavaPsiClassWrapper.kt
  src/main/kotlin/org/jetbrains/research/testspark/helpers/psi/java/JavaPsiHelper.kt
  src/main/kotlin/org/jetbrains/research/testspark/helpers/psi/java/JavaPsiMethodWrapper.kt
  src/main/kotlin/org/jetbrains/research/testspark/helpers/psiHelpers/JavaPsiHelper.kt
  src/main/kotlin/org/jetbrains/research/testspark/helpers/psiHelpers/PsiHelperFactory.kt
  src/main/kotlin/org/jetbrains/research/testspark/helpers/psiHelpers/PsiHelperInterface.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/Pipeline.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/evosuite/EvoSuite.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/Llm.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/PromptManager.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/template/Tool.kt
Labels: Ready for review, Urgent

#248 Update grazie-test-generation to version 1.0.5
  build.gradle.kts
Labels: improvement, Ready for review, Urgent

#250 Remove named variables for code type radio buttons
  src/main/kotlin/org/jetbrains/research/testspark/actions/TestSparkAction.kt
Labels: bug, Ready for review, Urgent

#246 Remove Java Stream API use in CoverageVisualisationService
  src/main/kotlin/org/jetbrains/research/testspark/services/CoverageVisualisationService.kt
Labels: refactoring, Urgent

#262 New project importer for headless mode
  build.gradle.kts
  core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/prompt/PromptGenerator.kt
  gradle.properties
  runTestSparkHeadless.sh
  src/main/kotlin/org/jetbrains/research/testspark/appstarter/ProjectApplicationUtils.kt
  src/main/kotlin/org/jetbrains/research/testspark/appstarter/TestSparkStarter.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/TestCompilerFactory.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/TestProcessor.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/ToolUtils.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/Llm.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/LLMProcessManager.kt
  src/main/resources/META-INF/plugin.xml
Labels: improvement, Ready for review, Urgent

#263 Introduce chat-role-sealed classes for `ChatMessage`
  core/src/main/kotlin/org/jetbrains/research/testspark/core/data/ChatMessage.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/network/RequestManager.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/grazie/GrazieRequestManager.kt
Labels: improvement, refactoring, Ready for review

#270 Rename variable in `LLMHelper.updateModelSelector` method: `modules` -> `models`
  src/main/kotlin/org/jetbrains/research/testspark/helpers/LLMHelper.kt
Labels: refactoring, Ready for review

#274 Fix typo in the plugin description page: to -> two
  src/main/kotlin/org/jetbrains/research/testspark/toolwindow/DescriptionTab.kt
Labels: documentation, Ready for review

#273 Move the HTTP request parsing into OpenAPI request manager
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/JUnitTestsAssembler.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/openai/OpenAIRequestManager.kt
Labels: refactoring, Ready for review

#264 [ICTL-975] Adjusting the plugin structure to enable different languages dependency
  .run/Run IDE for UI Tests.run.xml
  build.gradle.kts
  core/build.gradle.kts
  gradle.properties
  java/build.gradle.kts
  java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiClassWrapper.kt
  java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiHelper.kt
  java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiHelperProvider.kt
  java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiMethodWrapper.kt
  java/src/main/resources/META-INF/testgenie-java.xml
  kotlin/build.gradle.kts
  kotlin/src/main/kotlin/org/jetbrains/research/testspark/kotlin/KotlinPsiClassWrapper.kt
  kotlin/src/main/kotlin/org/jetbrains/research/testspark/kotlin/KotlinPsiHelper.kt
  kotlin/src/main/kotlin/org/jetbrains/research/testspark/kotlin/KotlinPsiHelperProvider.kt
  kotlin/src/main/kotlin/org/jetbrains/research/testspark/kotlin/KotlinPsiMethodWrapper.kt
  kotlin/src/main/resources/META-INF/testgenie-kotlin.xml
  langwrappers/build.gradle.kts
  langwrappers/src/main/kotlin/org/jetbrains/research/testspark/langwrappers/PsiComponents.kt
  langwrappers/src/main/kotlin/org/jetbrains/research/testspark/langwrappers/PsiHelperProvider.kt
  settings.gradle.kts
  src/main/kotlin/org/jetbrains/research/testspark/actions/TestSparkAction.kt
  src/main/kotlin/org/jetbrains/research/testspark/appstarter/TestSparkStarter.kt
  src/main/kotlin/org/jetbrains/research/testspark/helpers/LLMHelper.kt
  src/main/kotlin/org/jetbrains/research/testspark/helpers/psi/PsiHelperFactory.kt
  src/main/kotlin/org/jetbrains/research/testspark/services/CoverageVisualisationService.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/Pipeline.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/evosuite/EvoSuite.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/evosuite/EvoSuiteSettingsArguments.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/evosuite/generation/EvoSuiteProcessManager.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/Llm.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/LlmSettingsArguments.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/IJRequestManager.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/LLMProcessManager.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/PromptManager.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/RequestManagerFactory.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/grazie/GrazieRequestManager.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/openai/OpenAIRequestManager.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/template/Tool.kt
  src/main/resources/META-INF/plugin.xml
  src/test/kotlin/org/jetbrains/research/testspark/runner/SettingsArgumentsLlmEvoSuiteTest.kt
Labels: improvement, Ready for review, Urgent
