Repository JetBrains-Research/TestSpark, pull requests merged in 2024-07, with the labels that each got.

#284 Fix OpenAI bad request error on test generation request
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/grazie/GrazieRequestManager.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/openai/OpenAIRequestBody.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/openai/OpenAIRequestManager.kt
Labels: bug, Urgent

#255 Add instruction for polymorphism relations in PromptBuilder
  core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/prompt/PromptBuilder.kt
Labels: improvement, Ready for review

#287 Remove `Thread.sleep` in `OpenAIRequestManager`
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/openai/OpenAIRequestManager.kt
Labels: refactoring, Ready for review

#277 [ICTL-907] Parsing LLM Response for Kotlin tests (without UI representation and compilation)
  core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/LLMWithFeedbackCycle.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/Utils.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/network/RequestManager.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/Language.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/TestSuiteParser.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/TestSuiteParserStrategy.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/TestsAssembler.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/java/JavaJUnitTestSuiteParser.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/kotlin/KotlinJUnitTestSuiteParser.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/strategies/JUnitTestSuiteParserStrategy.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/utils/Patterns.kt
  core/src/test/kotlin/org/jetbrains/research/testspark/core/test/parsers/kotlin/KotlinJUnitTestSuiteParserTest.kt
  java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiClassWrapper.kt
  java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiHelper.kt
  kotlin/src/main/kotlin/org/jetbrains/research/testspark/kotlin/KotlinPsiClassWrapper.kt
  kotlin/src/main/kotlin/org/jetbrains/research/testspark/kotlin/KotlinPsiHelper.kt
  langwrappers/src/main/kotlin/org/jetbrains/research/testspark/langwrappers/LanguageClassTextExtractor.kt
  langwrappers/src/main/kotlin/org/jetbrains/research/testspark/langwrappers/PsiComponents.kt
  langwrappers/src/main/kotlin/org/jetbrains/research/testspark/langwrappers/strategies/JavaKotlinClassTextExtractor.kt
  src/main/kotlin/org/jetbrains/research/testspark/display/TestCasePanelFactory.kt
  src/main/kotlin/org/jetbrains/research/testspark/helpers/LLMHelper.kt
  src/main/kotlin/org/jetbrains/research/testspark/services/TestCaseDisplayService.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/Pipeline.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/Llm.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/JUnitTestsAssembler.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/LLMProcessManager.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/PromptManager.kt
Labels: improvement, Urgent

#282 [ICTL-908] Test Compiler for Kotlin
  build.gradle.kts
  core/src/main/kotlin/org/jetbrains/research/testspark/core/data/TestGenerationData.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/LLMWithFeedbackCycle.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/Utils.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/network/RequestManager.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/generation/llm/prompt/PromptBuilder.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/SupportedLanguage.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/TestBodyPrinter.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/TestCompiler.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/TestSuiteParser.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/TestSuiteParserStrategy.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/TestsAssembler.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/data/TestCaseGeneratedByLLM.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/data/TestSuiteGeneratedByLLM.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/data/dependencies/TestCompilationDependencies.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/java/JavaJUnitTestSuiteParser.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/java/JavaTestBodyPrinter.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/java/JavaTestCompiler.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/kotlin/KotlinJUnitTestSuiteParser.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/kotlin/KotlinTestBodyPrinter.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/kotlin/KotlinTestCompiler.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/strategies/JUnitTestSuiteParserStrategy.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/utils/Patterns.kt
  core/src/test/kotlin/org/jetbrains/research/testspark/core/test/parsers/kotlin/KotlinJUnitTestSuiteParserTest.kt
  java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiClassWrapper.kt
  java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiHelper.kt
  kotlin/src/main/kotlin/org/jetbrains/research/testspark/kotlin/KotlinPsiClassWrapper.kt
  kotlin/src/main/kotlin/org/jetbrains/research/testspark/kotlin/KotlinPsiHelper.kt
  langwrappers/src/main/kotlin/org/jetbrains/research/testspark/langwrappers/PsiComponents.kt
  src/main/kotlin/org/jetbrains/research/testspark/actions/TestSparkAction.kt
  src/main/kotlin/org/jetbrains/research/testspark/actions/llm/LLMSampleSelectorFactory.kt
  src/main/kotlin/org/jetbrains/research/testspark/actions/llm/TestSamplePanelFactory.kt
  src/main/kotlin/org/jetbrains/research/testspark/appstarter/TestSparkStarter.kt
  src/main/kotlin/org/jetbrains/research/testspark/display/TestCasePanelFactory.kt
  src/main/kotlin/org/jetbrains/research/testspark/display/TopButtonsPanelFactory.kt
  src/main/kotlin/org/jetbrains/research/testspark/display/strategies/TopButtonsPanelStrategy.kt
  src/main/kotlin/org/jetbrains/research/testspark/helpers/CoverageHelper.kt
  src/main/kotlin/org/jetbrains/research/testspark/helpers/LLMHelper.kt
  src/main/kotlin/org/jetbrains/research/testspark/helpers/TestClassBuilderHelper.kt
  src/main/kotlin/org/jetbrains/research/testspark/helpers/java/JavaClassBuilderHelper.kt
  src/main/kotlin/org/jetbrains/research/testspark/helpers/kotlin/KotlinClassBuilderHelper.kt
  src/main/kotlin/org/jetbrains/research/testspark/services/CoverageToolWindowDisplayService.kt
  src/main/kotlin/org/jetbrains/research/testspark/services/TestCaseDisplayService.kt
  src/main/kotlin/org/jetbrains/research/testspark/services/java/JavaTestCaseDisplayService.kt
  src/main/kotlin/org/jetbrains/research/testspark/services/kotlin/KotlinTestCaseDisplayService.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/LibraryPathsProvider.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/Pipeline.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/TestBodyPrinterFactory.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/TestCompilerFactory.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/TestProcessor.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/TestSuiteParserFactory.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/TestsAssemblerFactory.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/ToolUtils.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/evosuite/generation/EvoSuiteProcessManager.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/JUnitTestsAssembler.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/LLMProcessManager.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/PromptManager.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/test/JUnitTestSuitePresenter.kt
Labels: improvement, Urgent
