Repository JetBrains-Research/TestSpark, pull requests merged in 2024-08, with the labels that each got.

#318 [#311] Adding a stub for a problem with `kotlinc`
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/kotlin/KotlinTestCompiler.kt
Labels: bug

#309 [#300] Refactoring of TopButtonsPanelStrategy
  CONTRIBUTING.md
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/kotlin/KotlinTestCompiler.kt
  src/main/kotlin/org/jetbrains/research/testspark/display/TestSuiteView.kt
  src/main/kotlin/org/jetbrains/research/testspark/display/TopButtonsPanelFactory.kt
  src/main/kotlin/org/jetbrains/research/testspark/display/java/JavaTestSuiteView.kt
  src/main/kotlin/org/jetbrains/research/testspark/display/kotlin/KotlinTestSuiteView.kt
  src/main/kotlin/org/jetbrains/research/testspark/services/java/JavaTestCaseDisplayService.kt
  src/main/kotlin/org/jetbrains/research/testspark/services/kotlin/KotlinTestCaseDisplayService.kt
Labels: refactoring

#304 [#235] Renaming of the getSurroundingLine function
  CONTRIBUTING.md
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/kotlin/KotlinTestCompiler.kt
  java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiHelper.kt
  kotlin/src/main/kotlin/org/jetbrains/research/testspark/kotlin/KotlinPsiHelper.kt
  langwrappers/src/main/kotlin/org/jetbrains/research/testspark/langwrappers/PsiComponents.kt
  src/main/kotlin/org/jetbrains/research/testspark/display/TestSuiteView.kt
  src/main/kotlin/org/jetbrains/research/testspark/display/TopButtonsPanelFactory.kt
  src/main/kotlin/org/jetbrains/research/testspark/display/java/JavaTestSuiteView.kt
  src/main/kotlin/org/jetbrains/research/testspark/display/kotlin/KotlinTestSuiteView.kt
  src/main/kotlin/org/jetbrains/research/testspark/services/java/JavaTestCaseDisplayService.kt
  src/main/kotlin/org/jetbrains/research/testspark/services/kotlin/KotlinTestCaseDisplayService.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/evosuite/EvoSuite.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/Llm.kt
Labels: refactoring

#303 [#301] TestClassBuilderHelper refactoring
  CONTRIBUTING.md
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/TestsPersistentStorage.kt
  core/src/main/kotlin/org/jetbrains/research/testspark/core/test/kotlin/KotlinTestCompiler.kt
  java/src/main/kotlin/org/jetbrains/research/testspark/java/JavaPsiHelper.kt
  kotlin/src/main/kotlin/org/jetbrains/research/testspark/kotlin/KotlinPsiHelper.kt
  langwrappers/src/main/kotlin/org/jetbrains/research/testspark/langwrappers/PsiComponents.kt
  src/main/kotlin/org/jetbrains/research/testspark/appstarter/TestSparkStarter.kt
  src/main/kotlin/org/jetbrains/research/testspark/display/TestCasePanelFactory.kt
  src/main/kotlin/org/jetbrains/research/testspark/display/TestSuiteView.kt
  src/main/kotlin/org/jetbrains/research/testspark/display/TopButtonsPanelFactory.kt
  src/main/kotlin/org/jetbrains/research/testspark/display/java/JavaTestSuiteView.kt
  src/main/kotlin/org/jetbrains/research/testspark/display/kotlin/KotlinTestSuiteView.kt
  src/main/kotlin/org/jetbrains/research/testspark/helpers/LLMHelper.kt
  src/main/kotlin/org/jetbrains/research/testspark/helpers/TestClassBuilderHelper.kt
  src/main/kotlin/org/jetbrains/research/testspark/helpers/TestClassCodeAnalyzer.kt
  src/main/kotlin/org/jetbrains/research/testspark/helpers/TestClassCodeGenerator.kt
  src/main/kotlin/org/jetbrains/research/testspark/helpers/java/JavaTestClassCodeAnalyzer.kt
  src/main/kotlin/org/jetbrains/research/testspark/helpers/java/JavaTestClassCodeGenerator.kt
  src/main/kotlin/org/jetbrains/research/testspark/helpers/kotlin/KotlinTestClassCodeAnalyzer.kt
  src/main/kotlin/org/jetbrains/research/testspark/helpers/kotlin/KotlinTestClassCodeGenerator.kt
  src/main/kotlin/org/jetbrains/research/testspark/services/java/JavaTestCaseDisplayService.kt
  src/main/kotlin/org/jetbrains/research/testspark/services/kotlin/KotlinTestCaseDisplayService.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/TestBodyPrinterFactory.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/TestClassCodeAnalyzerFactory.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/TestClassCodeGeneratorFactory.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/TestCompilerFactory.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/TestsAssemblerFactory.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/ToolUtils.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/evosuite/EvoSuite.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/Llm.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/generation/LLMProcessManager.kt
  src/main/kotlin/org/jetbrains/research/testspark/tools/llm/test/JUnitTestSuitePresenter.kt
Labels: refactoring

#224 Fix error message window size
  src/main/kotlin/org/jetbrains/research/testspark/display/ErrorMessageNormalizer.kt
  src/main/kotlin/org/jetbrains/research/testspark/display/TestCasePanelFactory.kt
  src/test/kotlin/org/jetbrains/research/testspark/helper/ErrorMessageNormalizerTest.kt
Labels: Ready for review

#286 Add license & sources to core module publication
  core/build.gradle.kts
Labels: Ready for review

#323 Fix plugin logo issue
  src/main/resources/META-INF/pluginIcon_dark.svg
Labels: Ready for review, Urgent
