Repository JetBrains-Research/TestSpark, pull requests merged in 2024-12, with the labels that each got.

#414 Remove headless from development branch
  build.gradle.kts
  runTestSparkHeadless.sh
  src/main/kotlin/org/jetbrains/research/testspark/appstarter/ProjectApplicationUtils.kt
  src/main/kotlin/org/jetbrains/research/testspark/appstarter/TestSparkStarter.kt
  src/main/kotlin/org/jetbrains/research/testspark/progress/HeadlessProgressIndicator.kt
  src/main/resources/META-INF/plugin.xml
Labels: refactoring, Ready for review

#413 Resolving relative java path provided to EvoSuite
  src/main/kotlin/org/jetbrains/research/testspark/tools/evosuite/generation/EvoSuiteProcessManager.kt
Labels: improvement, Ready for review

#424 Add K2 support
  README.md
  build.gradle.kts
  src/main/resources/META-INF/plugin.xml
Labels: Ready for review

#421 Update Kotlin and IJ versions range
  build.gradle.kts
  gradle.properties
  src/test/kotlin/org/jetbrains/research/testspark/uiTest/utils/StepsLogger.kt
Labels: Ready for review
